interface Slide {
  image: string;
  text: string;
}

interface Post {
  image: string;
}

export const postList: Post[] = [
  {
    image: "/images/posts/1.jpg",
  },
  {
    image: "/images/posts/2.jpg",
  },
  {
    image: "/images/posts/3.jpg",
  },
  {
    image: "/images/posts/4.jpg",
  },
  {
    image: "/images/posts/5.jpg",
  },
];
export const slides: Slide[] = [
  {
    image: "/images/slider/1.jpg",
    text: "הטקסט מספר על ילדות בשכונת מוסררה בירושלים, שהייתה פעם שכונה פשוטה והפכה עם הזמן לשכונת יוקרה. המחבר מתאר את ההתרחשויות בשכונה, כמו התחלפות התושבים לברסלברים, והזכויות שהשכונה קמה לתחייה. המחבר גדל בסביבה עשירה בתרבויות ושפות שונות, כולל עברית, צרפתית, ספרדית, יידיש, ערבית מרוקאית ואנגלית, מה שהשפיע עליו באופן חיובי.",
  },
  {
    image: "/images/slider/2.jpg",
    text: "אהלן עולם! רוצה לחצות אותך, להגיע אל לב כולם, שישמעו, שיקשיבו, שידעו שזה בסדר להתבטא ולא לחתום שהכול טוב או רע.",
  },
  {
    image: "/images/slider/3.jpg",
    text: "יש דרך ויש לה המון ערך. כותבת חיים מלשמוע על אחרים, כותבת כי בעצמי חוצה אוקיינוסים כל רגע וגם בין רגע לרגע. מלחינה, שרה ויש לי כבר כמה שירים בערוצים כמו יוטיוב, אפל, ספוטיפיי ועוד.",
  },

  // Add more slides as needed
];

export const Options = {
  wallets: "wallets",
  boxes: "boxes",
  ashtrays: "ashtrays",
};

interface Creator {
  image: string;
  name: string;
  songsDesc: string[];
  description: string[];
}
export const creator: Creator = {
  image: "/images/orly1.jpg",
  name: "אורלי וייסמן",
  songsDesc: [
    "אהלן עולם",
    "רוצה לחצות אותך, להגיע אל לב כולם",
    "שישמעו שיקשיבו שידעו",
    "שזה בסדר להתבטא ולא לחתום שהכול טוב או רע",
    "יש דרך ויש לה המון ערך.",
    "",
    "כותבת חיים מלשמוע על אחרים",
    "כותבת כי בעצמי חוצה אוקיינוסים",
    "כל רגע וגם בין רגע לרגע",
    "מלחינה שרה ויש לי כבר כמה בכל מיני ערוצים.",
    "יוטיוב אפל ספוטיפיי ועוד...",
    "",
    "גדלתי בשכונת מורשה מוסררה בירושלים",
    "קמתי ונעמדתי על הרגליים",
    "והיום זו שכונת יוקרה, המחירים שברו את התקרה",
    "התושבים התחלפו מקיבוץ גלויות לברסלברים מלא ילדים",
    "השכונה מחדש קמה לתחיה!",
    "ואימי שתחיה בתוך כולם שומרת על הזכויות שלנו שם.",
    "",
    "גדלתי בין קידוש של ליל שבת מואזין מהמסגד",
    "ופעמוני כנסייה, הכל הצטלצל באוויר של ילדותי.",
    "מדי שבוע שמעתי את אבי בקריאה בתורה פיוטים...",
    "או אלתור על דרבוקה של אימי שתחיה ודודה של אבי זכרם לברכה.",
    "שמעתי עברית צרפתית ספרדית יידיש ערבית מרוקאית",
    "אנגלית. וכל זה השפיע הרבה טובה.",
    "מאורעות החיים הרשמים",
    "הכל נכתב נחתם!",
    "משפיע על הנשמה על הרוח...",
    "",
    "מגיע היום הפקק נפתח",
    "ויש צורך לעכל לבטא וליצור..",
    "",
    "כולנו בדרך 🩷",
  ],
  description: [
    "מתמחה בטיפול משולב תנועה מגע תזונה ורגש. מטפלת בשיטת אלבאום, מטפלת בקשיי תיפקוד פיזי וריגשי, בעיות קשב וריכוז ולמידה, ילדים ומבוגרים. טיפול זוגי, יחיד, פסיכותרפיה חסידית, טיפול בתנועה ומגע - פילאטיס, יוגה, ביילא פיטנס דנס, שיעורי מחול לנשים נערות וילדות.",

    "אהלן עולם! רוצה לחצות אותך, להגיע אל לב כולם, שישמעו, שיקשיבו, שידעו שזה בסדר להתבטא ולא לחתום שהכול טוב או רע. יש דרך ויש לה המון ערך. כותבת חיים מלשמוע על אחרים, כותבת כי בעצמי חוצה אוקיינוסים כל רגע וגם בין רגע לרגע. מלחינה, שרה ויש לי כבר כמה שירים בערוצים כמו יוטיוב, אפל, ספוטיפיי ועוד.",

    "גדלתי בשכונת מורשה מוסררה בירושלים. קמתי ונעמדתי על הרגליים והיום זו שכונת יוקרה, המחירים שברו את התקרה. התושבים התחלפו מקיבוץ גלויות לברסלברים מלא ילדים והשכונה מחדש קמה לתחיה! ואימי בתוך כולם שומרת על הזכויות שלנו שם. גדלתי בין קידוש של ליל שבת, מואזין מהמסגד ופעמוני כנסייה. הכל הצטלצל ביחד כשמדי פעם שמעתי קריאה בתורה פיוט או אלתור על דרבוקה של אימי שתחיה ודודה של אבי זיכרם לברכה. שמעתי עברית, צרפתית, ספרדית, יידיש, ערבית מרוקאית, אנגלית. וכל זה השפיע הרבה טובה.",

    "מוזמנים לחפש את שיריי: 'חרות' - זכותנו על הארץ, אימא אדמה, מולדת שלנו! 'מה זו אהבה' - הפער בין תחילת הדרך לדרך, התיסכול והייאוש. 'עליות ומורדות' - בחיי זוג. 'עמוק בתוך ליבך' - שפה מחברת, מעוררת את הלב, יכולה לרפא הרבה מאוד כאב ולקרב. 'לו הייתי ציפור' - כולנו זקוקים ליד שתנחה אותנו לחוף מבטחים. אם אהבתם, מוזמנים להגיב.",
  ],
};

export interface SongItem {
  id: string;
  image: string;
  title: string;
  description: string;
  youtubeLink: string;
  lyrics: string[];
  lyricsEn: string[];
  credits: string[];
}

export const songList: SongItem[] = [
  {
    id: "1",
    image: "/images/songs/freedom.png", // Replace with the actual path to the image
    title: "חירות",
    description:
      "חופש, חרות, במובן העמוק,מגיע אחרי דרך ארוכה. זו זכות ובחירה ועבודה פנימית עמוקה ואינטנסיבית..בפן האישי והלאומי. חשוב להכיר בזכות הזו שניתנה, זה גדול מכל אחד ואחת כאן ובעולם הנשמה שואפת למקום הטבעי שלה. אומי = אימי וגם האומה שלי. אומה- אומה כפשוטו, שלה שלו וגם אם. אומק= אימא אדמה ואם שלך ! כפי שאין ספק מי זו האם, כך אין ספק שזה הבית האדמה שלנו שלך שלך!",
    youtubeLink: "https://www.youtube.com/embed/_yNxbj9ePnQ",
    credits: [
      "מילים ולחן - אורלי ויסמן",
      "הפקה מוזיקלית ועיבוד - הראל חדד",
      "שירה - אורלי ויסמן",
      "קולות - רוניה צוויבל",
      "תופים, כלי הקשה, בוזוקי, בס, גיטרות ותכנותים - הראל חדד",
      'הוקלט באולפני גלים ע"י הראל חדד ושרון רייז',
      "מיקס ומסטר - הראל חדד",
      "גרפיקה ציור - בניהו יערי ויסמן",
      "גרפיקה - סיוון פסטרנק",
      "יעוץ - אבי מאור",
      "תמיכה - אישי היקר",
      'שפע ויכולת להעביר אותו הלאה - הקב"ה',
    ],
    lyrics: [
      "ימים רבים באופק מחכה",
      "על לוח לב היא חרותה",
      "ללא לאות חותר למטרה",
      "החופש הוא אוויר לנשמה",
      "",
      "שנים דורות רחיים על צוואר",
      "אומה או אם דואגת חרדה",
      "לילות הראש חושב",
      "איך להתיר את הכבלים",
      "להישאר שלם בא בימים",
      "",
      "בצאת ישראל ממצרים",
      "בית יעקב מעם לועז",
      "היתה יהודה לקדשו",
      "ישראל ממשלותיו",
      "",
      "עשורים חלפו עברו ביעף",
      "ממלכות עלו והתנדפו",
      "ארץ קטנטנה עומדת על תילה",
      "ההבטחה מברית בין הבתרים",
      "ישנה",
      "",
      "בצאת ישראל ממצרים",
      "בית יעקב מעם לועז",
      "היתה יהודה לקדשו",
      "ישראל ממשלותיו",
    ],
    lyricsEn: [
      "Many days on the horizon waiting",
      "Engraved upon our heart",
      "Tirelessly striving for the goal",
      "Freedom is air for the soul",
      "",
      "Years and generations a grinding stone on her neck",
      "A nation, a mother worries, anxious",
      "At night, her mind thinking",
      "How to untie the cables",
      "and stay whole in the fullness of days",
      "",
      "When Israel went out of Egypt",
      "the House of Jacob from a people of a foreign tongue,",
      "Judah became his sanctuary",
      "Israel his Dominion",
      "",
      "Decades have passed in a flash",
      "Kingdoms rose and evaporated",
      "A tiny country stands still",
      "The promise of the covenant still exists",
      "",
      "When Israel went out of Egypt",
      "the House of Jacob from a people of a foreign tongue,",
      "Judah became his sanctuary",
      "Israel his Dominion",
    ],
  },
  {
    id: "2",
    image: "/images/songs/deep.png",
    title: "עמוק בתוך ליבך",
    description: "10 Songs",
    youtubeLink: "https://www.youtube.com/embed/mItJYbn_qFA",
    credits: [
      "עמוק בתוך ליבך - קרדיטים",
      "הפקה מוזיקלית - הראל חדד",
      "מילים ולחן - אורלי ויסמן",
      "שירה, קולות - אורלי ויסמן",
      "תופים - תומר פרי",
      "גיטרות, בס, קלידים, תכנותים - הראל חדד",
      "כלי מיתר, עיבוד כלי מיתר - יועד ניר",
      "הקלטת כלי מיתר באולפן של יועד ניר",
      "מיקס ומסטרינג - הראל חדד",
      'הוקלט באולפני גלים ע"י הראל חדד ושרון רייז',
      "ציור - נתאי אלעזר ויסמן",
      "גרפיקה - סיוון פסטרנק",
      "הפצה דגיטאלית - Rad Star Management",
    ],
    lyrics: [
      "אם יכולתי להגיד מילים שמלטפות",
      "אם היה הכול רגיל הייתי רץ ללא לאות",
      "את השמש בחיי והשמיים בעניי",
      "קשה לי בדרכי אני בא אם תבקשי",
      "",
      "הפה ניפתח והאלם מחבל",
      "העלם שחזר יושב ומתאבל",
      "על ימים שכך היו ושנים שהתכלו",
      "משדה הקרב חזר הלום על חברו",
      "",
      "הלב שלי היה הלב שלי נפצע",
      "תמיד רוצה לחזור בחזרה",
      "אלבי נחרק אלבי תוואקף",
      "דיימן איכון בידי אלרוג'ע ולוועדה",
      "",
      "דעי שלעולם הפחד יישאר",
      "דעי אני הכול הכול אני זוכר",
      "יודע אהבה זו היא התקווה",
      "לעולם אנקוש על דלתה",
      "",
      "לעולם אנקוש על דלתה",
      "",
      "הלב שלי היה הלב שלי ניפצע",
      "תמיד רוצה לחזור בחזרה",
      "אלבי נחרק אלבי תוואקף",
      "דיימן איכון בידי אלרוג'ע ולוועדה",
      "",
      "וואנא קאמן בידי אשמע לורתק",
      "אילי מחבייה ראמיק ג'ואת אלבק",
      "אנא הון בסתאנה",
      "אנא הון בסתאנה",
      "",
      "גם אני רוצה לשמוע את שפתך",
      "שטמונה עמוק עמוק בתוך ליבך",
      "אהההא",
      "אהההא",
      "אההה",
    ],
    lyricsEn: [
      "If I could say words that caress",
      "If everything was normal I would run after you tirelessly",
      "You are the sun in my life and heaven in my eyes,",
      "It's hard for me, but I will come if you ask",
      "",
      "The mouth opens and the silence is overwhelming",
      "The lad who returned sits and mourns",
      "About the days that were and the years that have flown by",
      "From the battlefield he returned in shock about his friend",
      "",
      "My heart once was, my heart was injured",
      "I always want to go back",
      "Albi Nekhrak Albi Tawakf",
      "Dayman ikon bidi alruja walwa'ada",
      "",
      "Know that the fear will always remain",
      "Know, I remember everything, everything,",
      "I know this love is the hope",
      "I will forever knock on its door",
      "",
      "I will forever knock on its door",
      "",
      "My heart once was, my heart was injured",
      "I always want to go back",
      "Albi Nekhrak Albi Tawakf",
      "Dayman ikon bidi alruja walwa'ada",
      "",
      "I want to hear from you",
      "(In Arabic, same as above)",
      "",
      "I also want to hear your language",
      "that is hidden deep deep in your heart",
      "Ahahaha",
      "Ahahaha",
      "Ahhh",
    ],
  },

  {
    id: "3",
    image: "/images/songs/love.png", // Replace with the actual path to the image
    title: " מה זו אהבה",
    description: "5 Songs",
    youtubeLink: "https://www.youtube.com/embed/rjlyVWJA31I",
    credits: [
      "מילים ולחן - אורלי ויסמן",
      "",
      "הפקה ועיבוד מוזיקלי - הראל חדד",
      "שירה - אורלי ויסמן",
      "קולות - רוניה",
      "תופים - תומר פרי",
      "קלידים - איתמר שילה",
      "גיטרה קלאסית וכלי הקשה - הראל חדד",
      "גיטרה חשמלית - יוני חדד",
      "בס - יקיר ששון",
      "גרפיקה - נתאי אלעזר ושרה דליה ויסמן",
      "תמיכה - אישי היקר אברהם ויסמן",
      "תודה לריבונו של עולם שלא מוותר לי ועלי אף פעם.",
    ],
    lyrics: [
      "אוהב אותה שונא, רוצה אותו דוחה",
      "מגלה לו את ליבה.",
      "שותק במערה, שואלת מה נישמע",
      "לא מוכן להוציא מילה",
      "",
      "מה זו אהבה? מה זו אהבה",
      "",
      "נתן לה את כולו, אמרה לו רק שלו",
      "ופתאום היא לא רוצה",
      "הלכו למטפל, אמר להם טפל",
      "שבו ונוחו על הספה",
      "למי יש כאן תשובה? למי יש כאן תשובה",
      "",
      "הלכו ושוב חזרו רצו ולא רצו",
      "הם ביחד כך מיזמן",
      "שחוקים ועצבנים ויש כבר ילדים",
      "הם כמעט שמתפרקים",
      "אבאל'ה מה עושים? אבאל'ה מה עושים",
      "מה זו אהבה? מה זו אהבה",
      "",
      "רק רציתי להגיד שביחד נהדר",
      "רק רציתי לספר שביחד זה אפשר",
      "רק רציתי להגיד שביחד נהדר",
      "רק רציתי לספר שביחד זה אפשר",
      "רק רציתי להגיד שביחד נהדר",
      "רק רציתי לספר",
      "שאין כזה דבר",
      "",
      "אהבה",
      "מה זו אהבה",
    ],
    lyricsEn: [
      "Love her, hate her, want her, reject her",
      "She reveals her heart to him",
      "He's silent like in the cave, she's asking how are you?",
      "He's not ready to utter a word",
      "What is love? what is love?",
      "He gave her all of himself, she said she is only his",
      "And suddenly she doesn't want",
      "They went to a therapist, he said, its trivial",
      "Sit down and relax on the sofa",
      "Who has an answer here? Who has an answer here?",
      "",
      "They went and came back, they want and don’t wanting",
      "They are together like this for a long time",
      "Worn out and nervous they already have children",
      "They are almost falling apart",
      "But what do we do? Alas, what do we do?",
      "What is love? what is love",
      "",
      "I just wanted to say that together is great",
      "I just wanted to say that together it is possible",
      "I just wanted to say that together is great",
      "I just wanted to say that together it is possible",
      "I just wanted to say that together is great",
      "I just wanted to tell you",
      "there is no such thing",
      "",
      "Love",
      "what is love?",
    ],
  },

  {
    id: "4",
    image: "/images/songs/ups_downs.png",
    title: "עליות ומורדות",
    description: "10 Songs",
    youtubeLink: "https://www.youtube.com/embed/En-yPwDxLiU",
    credits: [
      "הפקה מוזיקלית - הראל חדד",
      "ציור עטיפה - נתאי אלעזר ויסמן",
      "גרפיקה - סיוון פסטרנק",
      "שירה - אורלי ויסמן",
      "קולות - הראל חדד, רוניה",
      "תופים - תומר פרי",
      "בס - יקיר ששון",
      "פסנתר - איתמר שילה",
      "גיטרה חשמלית - יוני חדד",
      "",
      "הוקלט באולפני גלים",
      "הקלטה ומיקס - הראל חדד",
    ],
    lyrics: [
      "הוא כאן לידי, אמר לי את שלי",
      "בטבעת חן הכתיר אותי",
      "בלילות כיבה את האור המנורה",
      "לא ראה שפתיי הרועדות",
      "לא הבחין עיניים מרצדות.",
      "שינה עמוקה טרפה הכול",
      "הלב אסף טיפות",
      "אלוקים לא מוותר על כלום",
      "נחל מתפרץ ניפתח לו לכאב",
      "נישאר איתי כאן לדבר שעות",
      "למה למה כך צריך להיות",
      "עליות ומורדות",
      "והרבה הרבה פשרות",
      "עליות ומורדות",
      "עם מבט עמוק נוכל להיות",
      "",
      "עברנו שנים רבות קשרנו גורלות",
      "מלך ומלכה הקמנו ממלכה",
      "הקירות שמעו לא מעט ראו",
      "בשקיעות שאגתי לא רוצה",
      "הכרזתי",
      "אתה לא רואה אותי",
      "עליות ומורדות",
      "והרבה הרבה פשרות",
      "עליות ומורדות",
      "עם מבט עמוק נוכל להיות",
      "עליות ומורדות",
      "והרבה הרבה פשרות",
      "עליות ומורדות",
      "עם מבט נוכל להיות",
    ],
    lyricsEn: [
      "He is here next to me, he told me you are mine",
      "He crowned me with a jeweled ring",
      "At night he turned off the light",
      "He didn't see my trembling lips",
      "Didn't notice my flickering eyes.",
      "Deep sleep devoured everything",
      "The heart collected drops",
      "God does not give up on anything",
      "An erupting stream opened for his pain",
      "We will stay here with me to talk for hours",
      "Why why should it be so",
      "Ups and downs",
      "And many, many compromises",
      "Ups and downs",
      "With a look deep inside we can be",
      "",
      "We have been through many years and tied our destinies",
      "A king and queen we have established a kingdom",
      "The walls heard quite a bit and saw the sunsets",
      "I roared, I do not want this, I announced",
      "You don't see me",
      "Ups and downs",
      "And many, many compromises",
      "Ups and downs",
      "With a look deep inside we can be",
      "",
      "Ups and downs",
      "And many, many compromises",
      "Ups and downs",
      "With a look deep inside we can be",
    ],
  },

  {
    id: "5",
    image: "/images/songs/bird.png", // Replace with the actual path to the image
    title: "לו הייתי ציפור",
    description: "5 Songs",
    youtubeLink: "https://www.youtube.com/embed/sykA_Q2mMns",
    credits: [
      "Producer, Mixing Engineer, Mastering Engineer: Harel Hadad",
      "Lyricist: Orly Weissman",
    ],
    lyrics: [],
    lyricsEn: [],
  },
];
